language: node_js
node_js:
  - 16
  - 17
  - 18
  - 19
  - 20
after_success: npm run coveralls
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: 20
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
